modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gopmod"
version="0.1.0"
displayName="GOP Modpack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ryanallen, MCreator"

[[dependencies.gopmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



